// WYGENEROWANE z scripts/page-texts/spec.mjs — nie edytuj ręcznie.
// Zmiany: popraw spec.mjs i uruchom `node scripts/page-texts/generate.mjs`.
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: "dream-map-settings",
  mode: 'single',
  label: { collection: { plural: "Strona: Ustrzyki 2036 (Mapa Marzeń)", singular: "Strona: Ustrzyki 2036 (Mapa Marzeń)" } },
  apiRoutes: { read: 'public' },
  dashboard: {
    icon: "Star",
    additionalRecordOptionsVueComponent: './app/dashboard/ViewOnSite.vue',
    fieldLayout: [{"Mapa nieba":["heroImage","skyTitle","skyTitleAccent","skySubtitle","skyInfoButton","skyInfoTitle","skyInfoText","skyInfoAuthor","skyInfoFooter","filterAll","filterCount","challengeLabel","solutionLabel","pageTitle"],"Skąd wzięła się mapa":["aboutKicker","aboutTitle","aboutImage","aboutText","fundingNote","fundingLogo1","fundingLogo2"],"Lista postulatów":["boardCount","boardTitle","boardLead"],"Zgłoś pomysł":["ideaKicker","ideaTitle","ideaText","ideaTileLink","ideaField1","ideaField2","ideaField3","ideaField4","ideaSubmit","ideaSending","ideaError","ideaSuccessTitle","ideaSuccessText","ideaAgain"],"Wygląd tej strony":["<./app/dashboard/ThemePreview.vue>","themeBackground","themeHero","themeTitle","themeLead","themeBody","themeAccent"]}],
  },
  fields: {
    heroImage: { type: 'image', options: {"required":false,"label":"Zdjęcie tła (nocne niebo)"} },
    skyTitle: { type: 'text', options: {"required":false,"label":"Tytuł — pierwsza część","default":"Cyfrowa Mapa"} },
    skyTitleAccent: { type: 'text', options: {"required":false,"label":"Tytuł — wyróżniona część","default":"Marzeń"} },
    skySubtitle: { type: 'text', options: {"required":false,"label":"Podtytuł","default":"Ustrzyki Dolne 2036 — Warsztat Przyszłości"} },
    skyInfoButton: { type: 'text', options: {"required":false,"label":"Przycisk informacji","default":"O projekcie"} },
    skyInfoTitle: { type: 'text', options: {"required":false,"label":"Okienko „O projekcie” — tytuł","default":"O projekcie"} },
    skyInfoText: { type: 'editor', options: {"required":false,"label":"Okienko „O projekcie” — tekst","default":"<p>Bieszczady to jedno z najciemniejszych miejsc na mapie Polski. Mieszkańcy Ustrzyk Dolnych spojrzeli w to niebo i rozłożyli na nim swoje marzenia o mieście za dekadę.</p><p>Każda gwiazda to postulat zgłoszony podczas warsztatów „Ustrzyki 2036: Warsztat Przyszłości”. Gwiazdozbiory łączą postulaty w kategorie tematyczne — kliknij gwiazdę, by poznać szczegóły.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    skyInfoAuthor: { type: 'text', options: {"required":false,"label":"Okienko — podpis","default":"Stowarzyszenie Nowoczesne Bieszczady"} },
    skyInfoFooter: { type: 'text', options: {"required":false,"label":"Okienko — stopka","description":"Strona sama wstawi liczbę w miejsce {liczba}.","default":"Projekt „Ustrzyki 2036: Warsztat Przyszłości” • 3 warsztaty kreatywne • {liczba} postulatów mieszkańców"} },
    filterAll: { type: 'text', options: {"required":false,"label":"Filtr „wszystkie”","default":"Wszystkie"} },
    filterCount: { type: 'text', options: {"required":false,"label":"Licznik w filtrze","description":"Strona sama wstawi liczbę w miejsce {liczba}.","default":"{liczba} postulatów"} },
    challengeLabel: { type: 'text', options: {"required":false,"label":"Etykieta wyzwania","default":"Wyzwanie"} },
    solutionLabel: { type: 'text', options: {"required":false,"label":"Etykieta rozwiązania","default":"Propozycja rozwiązania"} },
    pageTitle: { type: 'text', options: {"required":false,"label":"Tytuł w karcie przeglądarki","default":"Ustrzyki 2036: Warsztat Przyszłości"} },
    aboutKicker: { type: 'text', options: {"required":false,"label":"Napis nad tytułem","default":"Ustrzyki 2036: Warsztat Przyszłości"} },
    aboutTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Skąd wzięła się ta mapa"} },
    aboutImage: { type: 'image', options: {"required":false,"label":"Zdjęcie"} },
    aboutText: { type: 'editor', options: {"required":false,"label":"Tekst","default":"<p>Inicjatywa „Ustrzyki 2036: Warsztat Przyszłości” to autorski projekt realizowany przez Stowarzyszenie Nowoczesne Bieszczady we współpracy z lokalnymi partnerami: Centrum Koordynacji i Wspierania Aktywności Społeczno-Gospodarczej w Stefkowej oraz Powiatowym Urzędem Pracy w Ustrzykach Dolnych.</p><p>Główną intencją projektu było odejście od tradycyjnych, często biernych formuł konsultacji społecznych na rzecz stworzenia przestrzeni realnego, żywego i twórczego współdecydowania. Chcieliśmy dać mieszkańcom narzędzie do kształtowania przestrzeni publicznej oraz budowania poczucia sprawstwa — udowadniając, że głos każdego z nas ma znaczenie.</p><p>Prezentowana Cyfrowa Mapa Marzeń jest bezpośrednim owocem procesu konsultacji społecznych i pracy warsztatowej. Przy jednym stole usiedli przedstawiciele bardzo różnych środowisk — od seniorów dzielących się mądrością życiową, przez lokalnych liderów i członków organizacji pozarządowych, aż po młodzież z Młodzieżowej Rady Gminy.</p><p>Niniejsza mapa nie jest katalogiem roszczeń ani formą krytyki dotychczasowych działań. Jest głosem troski, dojrzałej odpowiedzialności oraz autentycznej miłości do naszej małej ojczyzny. Traktujemy wypracowane postulaty jako partnerskie zaproszenie do dialogu.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    fundingNote: { type: 'text-area', options: {"required":false,"label":"Informacja o finansowaniu","default":"Inicjatywa jest współfinansowana ze środków otrzymanych od Narodowego Instytutu Wolności — Centrum Rozwoju Społeczeństwa Obywatelskiego w ramach Rządowego Programu Fundusz Inicjatyw Obywatelskich NOWEFIO na lata 2021–2030, za pośrednictwem Stowarzyszenia „Pro Carpathia”.","rows":4} },
    fundingLogo1: { type: 'image', options: {"required":false,"label":"Logo finansowania 1","description":"NIW / NOWEFIO"} },
    fundingLogo2: { type: 'image', options: {"required":false,"label":"Logo finansowania 2","description":"Pro Carpathia"} },
    boardCount: { type: 'text', options: {"required":false,"label":"Napis nad tytułem","description":"Strona sama wstawi liczbę w miejsce {liczba}.","default":"{liczba} postulatów mieszkańców"} },
    boardTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Wszystkie punkty mapy marzeń"} },
    boardLead: { type: 'text-area', options: {"required":false,"label":"Opis","default":"Pełna lista wniosków i rekomendacji z warsztatów „Ustrzyki 2036” — wyzwanie i proponowane rozwiązanie przy każdym punkcie.","rows":2} },
    ideaKicker: { type: 'text', options: {"required":false,"label":"Napis nad tytułem","default":"Twój głos"} },
    ideaTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Zgłoś swój pomysł"} },
    ideaText: { type: 'text-area', options: {"required":false,"label":"Opis","default":"Masz pomysł, jak zmienić Ustrzyki Dolne na lepsze? Opisz go — przeczytamy każde zgłoszenie.","rows":2} },
    ideaTileLink: { type: 'text', options: {"required":false,"label":"Link na kafelku","default":"Zgłoś pomysł →"} },
    ideaField1: { type: 'text', options: {"required":false,"label":"Pole 1","default":"1. Tytuł pomysłu"} },
    ideaField2: { type: 'text', options: {"required":false,"label":"Pole 2","default":"2. Opis problemu do rozwiązania"} },
    ideaField3: { type: 'text', options: {"required":false,"label":"Pole 3","default":"3. Propozycja rozwiązania / Twój pomysł"} },
    ideaField4: { type: 'text', options: {"required":false,"label":"Pole 4","default":"4. Kontakt (e-mail lub telefon)"} },
    ideaSubmit: { type: 'text', options: {"required":false,"label":"Przycisk wysyłania","default":"Wyślij pomysł"} },
    ideaSending: { type: 'text', options: {"required":false,"label":"Podczas wysyłania","default":"Wysyłanie…"} },
    ideaError: { type: 'text', options: {"required":false,"label":"Gdy się nie uda","default":"Nie udało się wysłać zgłoszenia. Spróbuj ponownie za chwilę."} },
    ideaSuccessTitle: { type: 'text', options: {"required":false,"label":"Po wysłaniu — tytuł","default":"Dziękujemy!"} },
    ideaSuccessText: { type: 'text-area', options: {"required":false,"label":"Po wysłaniu — tekst","default":"Twój pomysł do nas dotarł. Skontaktujemy się, jeśli będziemy mieli pytania.","rows":2} },
    ideaAgain: { type: 'text', options: {"required":false,"label":"Przycisk kolejnego zgłoszenia","default":"Zgłoś kolejny pomysł"} },
    themeBackground: { type: 'color', options: {"required":false,"label":"Tło strony","description":"Tło całej treści tej podstrony.","default":""} },
    themeHero: { type: 'color', options: {"required":false,"label":"Tło nagłówka","description":"Tło górnej części z tytułem podstrony.","default":""} },
    themeTitle: { type: 'color', options: {"required":false,"label":"Tytuły i nagłówki","description":"Tytuł podstrony, tytuły sekcji i kart.","default":""} },
    themeLead: { type: 'color', options: {"required":false,"label":"Opisy wyróżnione (wstępy)","description":"Pierwszy akapit opisów i teksty pod tytułami sekcji.","default":""} },
    themeBody: { type: 'color', options: {"required":false,"label":"Zwykły tekst","description":"Akapity w opisach i na kartach.","default":""} },
    themeAccent: { type: 'color', options: {"required":false,"label":"Akcent: przyciski, linki, napisy nad tytułami","default":""} },
  },
})
