// WYGENEROWANE z scripts/page-texts/spec.mjs — nie edytuj ręcznie.
// Zmiany: popraw spec.mjs i uruchom `node scripts/page-texts/generate.mjs`.
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: "site-settings",
  mode: 'single',
  label: { collection: { plural: "Elementy wspólne i kontakt", singular: "Elementy wspólne i kontakt" } },
  apiRoutes: { read: 'public' },
  dashboard: {
    icon: "Settings",
    additionalRecordOptionsVueComponent: './app/dashboard/ViewOnSite.vue',
    fieldLayout: [{"Kontakt":["logo","email","phone","address","facebookUrl","facebookLabel"],"Stopka":["footerTitle","footerTagline","footerDownloads","footerCopyright"],"Karty i przyciski":["readMore","readFull","readLess","relatedKicker","relatedTitle","relatedAll","siteName"],"Galerie":["galleryShowAll","gallerySwipe","galleryExpand","galleryCollapse"],"Wygląd strony":["<./app/dashboard/ThemePreview.vue>","colorTitle","colorLead","colorBody","colorExtra","colorAccent","colorBrand","colorInk","colorBackground","colorSection","colorEasy","colorMedium","colorHard"],"Trasy — nazwy":["difficultyEasy","difficultyMedium","difficultyHard","bikeMtb","bikeGravel","bikeEbike","bikeRoad","cardElevation"]}],
  },
  fields: {
    logo: { type: 'image', options: {"required":false,"label":"Logo (ikona)","description":"W nagłówku i stopce."} },
    email: { type: 'text', options: {"required":false,"label":"Adres e-mail","default":"biuro@nowoczesnebieszczady.pl"} },
    phone: { type: 'text', options: {"required":false,"label":"Telefon","default":"507 068 728"} },
    address: { type: 'text', options: {"required":false,"label":"Adres","default":"Ustrzyki Dolne, woj. podkarpackie"} },
    facebookUrl: { type: 'text', options: {"required":false,"label":"Facebook (adres strony)","default":"https://www.facebook.com/nowoczesne.bieszczady/?locale=pl_PL","placeholder":"np. /aktualnosci albo https://…"} },
    facebookLabel: { type: 'text', options: {"required":false,"label":"Napis „Facebook”","default":"Facebook"} },
    footerTitle: { type: 'text', options: {"required":false,"label":"Nazwa w stopce","default":"NOWOCZESNE BIESZCZADY"} },
    footerTagline: { type: 'text', options: {"required":false,"label":"Opis pod nazwą","default":"Stowarzyszenie działające na rzecz rozwoju regionu"} },
    footerDownloads: { type: 'text', options: {"required":false,"label":"Nagłówek listy dokumentów","default":"Do pobrania"} },
    footerCopyright: { type: 'text', options: {"required":false,"label":"Prawa autorskie","description":"Strona sama wstawi bieżący rok w miejsce {rok}.","default":"© {rok} Nowoczesne Bieszczady. Wszystkie prawa zastrzeżone."} },
    readMore: { type: 'text', options: {"required":false,"label":"„Czytaj więcej” na kartach wpisów","default":"Czytaj więcej →"} },
    readFull: { type: 'text', options: {"required":false,"label":"Rozwijanie długiego opisu","default":"Czytaj całość"} },
    readLess: { type: 'text', options: {"required":false,"label":"Zwijanie długiego opisu","default":"Zwiń"} },
    relatedKicker: { type: 'text', options: {"required":false,"label":"Powiązane aktualności — napis nad tytułem","default":"Aktualności"} },
    relatedTitle: { type: 'text', options: {"required":false,"label":"Powiązane aktualności — tytuł","description":"Sekcja na podstronach z wpisami, przy których zaznaczono „Pokaż także na podstronach”.","default":"Powiązane aktualności"} },
    relatedAll: { type: 'text', options: {"required":false,"label":"Powiązane aktualności — link do wszystkich","default":"Zobacz wszystkie aktualności →"} },
    siteName: { type: 'text', options: {"required":false,"label":"Nazwa strony w karcie przeglądarki","description":"Dopisywana po tytule podstrony, np. „Aktualności — Nowoczesne Bieszczady”.","default":"Nowoczesne Bieszczady"} },
    galleryShowAll: { type: 'text', options: {"required":false,"label":"Na ostatnim kafelku mozaiki","default":"Zobacz wszystkie"} },
    gallerySwipe: { type: 'text', options: {"required":false,"label":"Podpowiedź na telefonie","default":"Przesuń, aby zobaczyć więcej →"} },
    galleryExpand: { type: 'text', options: {"required":false,"label":"Przycisk rozwijający galerię","description":"Strona sama wstawi liczbę w miejsce {liczba}.","default":"Pokaż wszystkie zdjęcia ({liczba})"} },
    galleryCollapse: { type: 'text', options: {"required":false,"label":"Przycisk zwijający galerię","default":"Zwiń galerię"} },
    colorTitle: { type: 'color', options: {"required":false,"label":"Tytuły i nagłówki","description":"Np. „Krótko o nas”, tytuły sekcji i kart.","default":"#151d1c"} },
    colorLead: { type: 'color', options: {"required":false,"label":"Tekst wyróżniony (wstępy)","description":"Pierwszy akapit opisów i duże zdania.","default":"#566c71"} },
    colorBody: { type: 'color', options: {"required":false,"label":"Zwykły tekst","description":"Akapity w opisach i kartach.","default":"#6c7173"} },
    colorExtra: { type: 'color', options: {"required":false,"label":"Tekst dodatkowy (pytania)","description":"Np. „Czym się zajmujemy?”.","default":"#615b3a"} },
    colorAccent: { type: 'color', options: {"required":false,"label":"Akcent: przyciski, numery, linki","description":"Pomarańczowe przyciski, małe napisy nad tytułami, linki.","default":"#a8551f"} },
    colorBrand: { type: 'color', options: {"required":false,"label":"Kolor marki (tytuły podstron, liczniki)","default":"#135e24"} },
    colorInk: { type: 'color', options: {"required":false,"label":"Ciemny kolor (menu, stopka, główne napisy)","default":"#1a2420"} },
    colorBackground: { type: 'color', options: {"required":false,"label":"Tło strony","default":"#eff2ef"} },
    colorSection: { type: 'color', options: {"required":false,"label":"Tło nagłówków podstron","default":"#f3f1ea"} },
    colorEasy: { type: 'color', options: {"required":false,"label":"Trasy łatwe (mapa i oznaczenia)","default":"#0072bd"} },
    colorMedium: { type: 'color', options: {"required":false,"label":"Trasy średnie (mapa i oznaczenia)","default":"#9c27b0"} },
    colorHard: { type: 'color', options: {"required":false,"label":"Trasy trudne (mapa i oznaczenia)","default":"#cc0000"} },
    difficultyEasy: { type: 'text', options: {"required":false,"label":"Trudność: łatwa","default":"Łatwa"} },
    difficultyMedium: { type: 'text', options: {"required":false,"label":"Trudność: średnia","default":"Średnia"} },
    difficultyHard: { type: 'text', options: {"required":false,"label":"Trudność: trudna","default":"Trudna"} },
    bikeMtb: { type: 'text', options: {"required":false,"label":"Rower: MTB","default":"MTB"} },
    bikeGravel: { type: 'text', options: {"required":false,"label":"Rower: gravel","default":"Gravel"} },
    bikeEbike: { type: 'text', options: {"required":false,"label":"Rower: e-bike","default":"E-bike"} },
    bikeRoad: { type: 'text', options: {"required":false,"label":"Rower: szosa","default":"Szosa"} },
    cardElevation: { type: 'text', options: {"required":false,"label":"Na karcie trasy: przewyższenia","description":"Strona sama wstawi liczbę w miejsce {liczba}.","default":"{liczba} m przewyższeń"} },
  },
})
