// WYGENEROWANE z scripts/page-texts/spec.mjs — nie edytuj ręcznie.
// Zmiany: popraw spec.mjs i uruchom `node scripts/page-texts/generate.mjs`.
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: "strona-o-nas",
  mode: 'single',
  label: { collection: { plural: "Strona: O nas", singular: "Strona: O nas" } },
  apiRoutes: { read: 'public' },
  dashboard: {
    icon: "Users",
    additionalRecordOptionsVueComponent: './app/dashboard/ViewOnSite.vue',
    fieldLayout: [{"Nagłówek":["heroKicker","heroTitle","heroDescription","stats"],"Kim jesteśmy / Misja":["misjaTitle","misjaText","misjaPageTitle"],"Cele":["celeTitle","celeText","goals"],"Statut":["statutTitle","statutText","statutFile","statutDownload","statutOpen","statutHint","statutPages"],"Deklaracja":["deklaracjaTitle","deklaracjaText","deklaracjaFile","deklaracjaDownload","deklaracjaSoon","deklaracjaStep1","deklaracjaStep2","deklaracjaStep3"],"Zarząd i Zespół":["zarzadTitle","zarzadText","team"],"Sprawozdania":["sprawozdaniaTitle","sprawozdaniaText","sprawozdaniaDownload","sprawozdaniaSoon"],"Partnerzy":["partnerzyTitle","partnerzyText","partners"],"Wolontariat":["wolontariatTitle","wolontariatText","wolontariatDocs","wolontariatEmpty","wolontariatOpen"],"Wygląd tej strony":["<./app/dashboard/ThemePreview.vue>","themeBackground","themeHero","themeTitle","themeLead","themeBody","themeAccent"]}],
  },
  fields: {
    heroKicker: { type: 'text', options: {"required":false,"label":"Napis nad tytułem","default":"Stowarzyszenie"} },
    heroTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"O nas"} },
    heroDescription: { type: 'editor', options: {"required":false,"label":"Opis","default":"<p>Kim jesteśmy, czym się kierujemy i jak działamy na rzecz Bieszczadów.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    stats: { type: 'text-area', options: {"required":false,"label":"Napisy pod tytułem","description":"Jeden napis w linii.","default":"Od 2016 roku\n4 obszary działania\nUstrzyki Dolne","rows":3} },
    misjaTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Kim jesteśmy / Nasza Misja"} },
    misjaText: { type: 'editor', options: {"required":false,"label":"Tekst","default":"<p>Stowarzyszenie Nowoczesne Bieszczady powstało w 2016 roku w Ustrzykach Dolnych. Prowadzimy działalność doradczą, edukacyjną i kulturalną — wspieramy ekonomię społeczną, edukację demokracji lokalnej, aktywność kulturalną oraz rozwój Ustrzyk Dolnych i Powiatu Bieszczadzkiego.</p><p>Naszą misją jest łączenie tradycji z nowoczesnością — pokazywanie, że zrównoważony rozwój Bieszczadów może iść w parze z nowymi technologiami, aktywizacją społeczną i otwartością na zmiany. Wierzymy, że najlepsze pomysły rodzą się we współpracy z mieszkańcami, dlatego większość naszych projektów opiera się na dialogu i realnym udziale lokalnej społeczności.</p><p>Nasi członkowie to przedsiębiorcy, nauczyciele, pracownicy samorządowi i specjaliści różnych branż. Stawiamy na profesjonalizm i zaangażowanie — „Skuteczni dla Was”.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    misjaPageTitle: { type: 'text', options: {"required":false,"label":"Tytuł w karcie przeglądarki","default":"Kim jesteśmy"} },
    celeTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Cele Stowarzyszenia"} },
    celeText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Nasza działalność koncentruje się wokół czterech głównych obszarów:</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    goals: { type: 'repeater', options: { ...{"required":false,"label":"Cele","description":"Kliknij „Dodaj cel”. Kolejność zmienisz, przeciągając wpisy.","addLabel":"Dodaj cel"}, subfields: {"title":{"type":"text","options":{"required":true,"label":"Tytuł"}},"description":{"type":"text-area","options":{"required":false,"label":"Opis","rows":3}}} } },
    statutTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Statut Stowarzyszenia"} },
    statutText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Statut Stowarzyszenia Nowoczesne Bieszczady określa cele, zasady działania oraz strukturę organizacyjną naszej organizacji. Pełną treść dokumentu można przeczytać poniżej lub pobrać jako plik PDF.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    statutFile: { type: 'file', options: {"required":false,"label":"Plik statutu (PDF)","description":"Wgraj plik — przyciski „Pobierz” i „Otwórz” będą go używać."} },
    statutDownload: { type: 'text', options: {"required":false,"label":"Przycisk pobierania","default":"Pobierz Statut (PDF)"} },
    statutOpen: { type: 'text', options: {"required":false,"label":"Przycisk otwierania","default":"Otwórz w nowej karcie"} },
    statutHint: { type: 'text', options: {"required":false,"label":"Podpowiedź nad stronami","default":"Kliknij stronę, żeby ją powiększyć."} },
    statutPages: { type: 'gallery', options: {"required":false,"label":"Strony statutu (zdjęcia)","description":"Zdjęcia kolejnych stron statutu — przeciągnij, aby ustawić kolejność.","directory":"o-nas/statut/"} },
    deklaracjaTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Deklaracja członkowska"} },
    deklaracjaText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Chcesz dołączyć do Stowarzyszenia Nowoczesne Bieszczady? Pobierz i wypełnij deklarację członkowską, a następnie dostarcz ją osobiście lub prześlij skan na adres e-mail biura stowarzyszenia.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    deklaracjaFile: { type: 'file', options: {"required":false,"label":"Plik deklaracji (PDF)","description":"Gdy plik jest wgrany, pokazuje się przycisk pobierania."} },
    deklaracjaDownload: { type: 'text', options: {"required":false,"label":"Przycisk pobierania","default":"Pobierz deklarację (PDF)"} },
    deklaracjaSoon: { type: 'text', options: {"required":false,"label":"Gdy pliku jeszcze nie ma","default":"Formularz wkrótce dostępny"} },
    deklaracjaStep1: { type: 'text', options: {"required":false,"label":"Krok 1","default":"Pobierz i wypełnij formularz deklaracji."} },
    deklaracjaStep2: { type: 'text', options: {"required":false,"label":"Krok 2","default":"Podpisz dokument odręcznie lub elektronicznie."} },
    deklaracjaStep3: { type: 'text', options: {"required":false,"label":"Krok 3","description":"Strona sama wstawi adres e-mail z „Elementów wspólnych” w miejsce {email}.","default":"Prześlij skan na {email} lub dostarcz osobiście."} },
    zarzadTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Zarząd i Zespół"} },
    zarzadText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Poznaj osoby, które na co dzień koordynują działania Stowarzyszenia Nowoczesne Bieszczady.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    team: { type: 'repeater', options: { ...{"required":false,"label":"Osoby","description":"Kliknij „Dodaj osobę”. Kolejność zmienisz, przeciągając wpisy.","addLabel":"Dodaj osobę"}, subfields: {"name":{"type":"text","options":{"required":true,"label":"Imię i nazwisko"}},"role":{"type":"text","options":{"required":false,"label":"Funkcja","placeholder":"np. Prezes Zarządu"}},"photo":{"type":"image","options":{"required":false,"label":"Zdjęcie"}}} } },
    sprawozdaniaTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Sprawozdania i transparentność"} },
    sprawozdaniaText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Transparentność jest dla nas kluczowa. Poniżej publikujemy coroczne sprawozdania merytoryczne i finansowe Stowarzyszenia Nowoczesne Bieszczady.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    sprawozdaniaDownload: { type: 'text', options: {"required":false,"label":"Przycisk pobierania","default":"Pobierz PDF"} },
    sprawozdaniaSoon: { type: 'text', options: {"required":false,"label":"Gdy pliku jeszcze nie ma","default":"PDF wkrótce"} },
    partnerzyTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Partnerzy i Grantodawcy"} },
    partnerzyText: { type: 'editor', options: {"required":false,"label":"Wstęp","default":"<p>Nasze projekty realizujemy dzięki współpracy i wsparciu finansowemu poniższych instytucji i organizacji.</p>","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    partners: { type: 'repeater', options: { ...{"required":false,"label":"Partnerzy i grantodawcy","description":"Kliknij „Dodaj partnera”. Kolejność zmienisz, przeciągając wpisy.","addLabel":"Dodaj partnera"}, subfields: {"name":{"type":"text","options":{"required":true,"label":"Nazwa"}},"logo":{"type":"image","options":{"required":false,"label":"Logo"}},"url":{"type":"text","options":{"required":false,"label":"Strona internetowa (opcjonalnie)","placeholder":"https://…"}}} } },
    wolontariatTitle: { type: 'text', options: {"required":false,"label":"Tytuł","default":"Wolontariat"} },
    wolontariatText: { type: 'editor', options: {"required":false,"label":"Opis","toolbar":["heading2","heading3","paragraph","bold","italic","link","bulletList","orderedList","blockquote","clear","undo","redo"]} },
    wolontariatDocs: { type: 'repeater', options: { ...{"required":false,"label":"Dokumenty do pobrania","description":"Kliknij „Dodaj dokument”, wpisz nazwę i wgraj plik (np. PDF). Kolejność zmienisz, przeciągając wpisy.","addLabel":"Dodaj dokument"}, subfields: {"label":{"type":"text","options":{"required":true,"label":"Nazwa dokumentu","placeholder":"np. Porozumienie wolontariackie"}},"file":{"type":"file","options":{"required":true,"label":"Plik"}}} } },
    wolontariatEmpty: { type: 'text-area', options: {"required":false,"label":"Gdy opis wolontariatu jest pusty","description":"Pokazuje się, gdy opis powyżej jest pusty.","default":"Wkrótce zamieścimy tutaj informacje o wolontariacie w Stowarzyszeniu Nowoczesne Bieszczady.","rows":2} },
    wolontariatOpen: { type: 'text', options: {"required":false,"label":"Przycisk przy dokumencie","default":"Pobierz / zobacz"} },
    themeBackground: { type: 'color', options: {"required":false,"label":"Tło strony","description":"Tło całej treści tej podstrony.","default":""} },
    themeHero: { type: 'color', options: {"required":false,"label":"Tło nagłówka","description":"Tło górnej części z tytułem podstrony.","default":""} },
    themeTitle: { type: 'color', options: {"required":false,"label":"Tytuły i nagłówki","description":"Tytuł podstrony, tytuły sekcji i kart.","default":""} },
    themeLead: { type: 'color', options: {"required":false,"label":"Opisy wyróżnione (wstępy)","description":"Pierwszy akapit opisów i teksty pod tytułami sekcji.","default":""} },
    themeBody: { type: 'color', options: {"required":false,"label":"Zwykły tekst","description":"Akapity w opisach i na kartach.","default":""} },
    themeAccent: { type: 'color', options: {"required":false,"label":"Akcent: przyciski, linki, napisy nad tytułami","default":""} },
  },
})
