// WYGENEROWANE z scripts/page-texts/spec.mjs — nie edytuj ręcznie.
// Zmiany: popraw spec.mjs i uruchom `node scripts/page-texts/generate.mjs`.
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: "strona-trasa",
  mode: 'single',
  label: { collection: { plural: "Strona: Pojedyncza trasa", singular: "Strona: Pojedyncza trasa" } },
  apiRoutes: { read: 'public' },
  dashboard: {
    icon: "MapPin",
    fieldLayout: [{"Plik GPX":["gpxTitle","gpxText","gpxButton","gpxSoon"],"Podstawowe informacje":["infoTitle","rowName","rowStart","rowCharacter","rowLength","rowElevation","rowRange","rowRangeUnit","rowTime","rowDifficulty","rowBike","rowSurface"],"Nagłówki sekcji":["elevationTitle","elevationNote","mapTitle","descriptionTitle","overviewLabel","waypointsTitle","waypointsKm","waypointsPoint","waypointsMeaning","highlightsTitle","stopsTitle","natureTitle","cultureTitle","surfaceTitle","surfaceAsphalt","surfaceGravel","surfaceTerrain","touristTitle","recommendationTitle","safetyTitle","backLink","notFound"]}],
  },
  fields: {
    gpxTitle: { type: 'text', options: {"required":false,"label":"Nagłówek","default":"Pobierz nawigację GPX"} },
    gpxText: { type: 'text', options: {"required":false,"label":"Opis","default":"Plik do wgrania na nawigację rowerową lub zegarek GPS."} },
    gpxButton: { type: 'text', options: {"required":false,"label":"Przycisk pobierania","default":"Pobierz plik GPX"} },
    gpxSoon: { type: 'text', options: {"required":false,"label":"Gdy pliku jeszcze nie ma","default":"GPX wkrótce dostępny"} },
    infoTitle: { type: 'text', options: {"required":false,"label":"Nagłówek sekcji","default":"Podstawowe informacje"} },
    rowName: { type: 'text', options: {"required":false,"label":"Wiersz: nazwa","default":"Nazwa trasy"} },
    rowStart: { type: 'text', options: {"required":false,"label":"Wiersz: start/meta","default":"Punkt startu/mety"} },
    rowCharacter: { type: 'text', options: {"required":false,"label":"Wiersz: charakter","default":"Charakter trasy"} },
    rowLength: { type: 'text', options: {"required":false,"label":"Wiersz: długość","default":"Długość z GPX"} },
    rowElevation: { type: 'text', options: {"required":false,"label":"Wiersz: przewyższenia","default":"Przewyższenia z GPX"} },
    rowRange: { type: 'text', options: {"required":false,"label":"Wiersz: zakres wysokości","default":"Zakres wysokości"} },
    rowRangeUnit: { type: 'text', options: {"required":false,"label":"Jednostka zakresu","default":"m n.p.m."} },
    rowTime: { type: 'text', options: {"required":false,"label":"Wiersz: czas","default":"Szacowany czas przejazdu"} },
    rowDifficulty: { type: 'text', options: {"required":false,"label":"Wiersz: trudność","default":"Poziom trudności"} },
    rowBike: { type: 'text', options: {"required":false,"label":"Wiersz: rower","default":"Rekomendowany rower"} },
    rowSurface: { type: 'text', options: {"required":false,"label":"Wiersz: nawierzchnia","default":"Nawierzchnia"} },
    elevationTitle: { type: 'text', options: {"required":false,"label":"Profil wysokościowy","default":"Profil wysokościowy"} },
    elevationNote: { type: 'text', options: {"required":false,"label":"Podpis pod wykresem poglądowym","default":"Wykres poglądowy — pełne dane wysokościowe dostępne w pliku GPX."} },
    mapTitle: { type: 'text', options: {"required":false,"label":"Mapa przebiegu","default":"Mapa przebiegu trasy"} },
    descriptionTitle: { type: 'text', options: {"required":false,"label":"Opis trasy","default":"Opis trasy"} },
    overviewLabel: { type: 'text', options: {"required":false,"label":"Etykieta przebiegu","default":"Przebieg trasy:"} },
    waypointsTitle: { type: 'text', options: {"required":false,"label":"Najważniejsze punkty","default":"Najważniejsze punkty na trasie"} },
    waypointsKm: { type: 'text', options: {"required":false,"label":"Kolumna: km","default":"Km"} },
    waypointsPoint: { type: 'text', options: {"required":false,"label":"Kolumna: punkt","default":"Punkt / miejscowość"} },
    waypointsMeaning: { type: 'text', options: {"required":false,"label":"Kolumna: znaczenie","default":"Znaczenie"} },
    highlightsTitle: { type: 'text', options: {"required":false,"label":"Co warto zobaczyć","default":"Co warto zobaczyć"} },
    stopsTitle: { type: 'text', options: {"required":false,"label":"Odpoczynek i gastronomia","default":"Miejsca odpoczynku i gastronomia"} },
    natureTitle: { type: 'text', options: {"required":false,"label":"Walory przyrodnicze","default":"Walory przyrodnicze"} },
    cultureTitle: { type: 'text', options: {"required":false,"label":"Walory kulturowe","default":"Walory historyczne i kulturowe"} },
    surfaceTitle: { type: 'text', options: {"required":false,"label":"Nawierzchnia","default":"Nawierzchnia"} },
    surfaceAsphalt: { type: 'text', options: {"required":false,"label":"Asfalt","default":"Asfalt"} },
    surfaceGravel: { type: 'text', options: {"required":false,"label":"Szuter","default":"Szuter"} },
    surfaceTerrain: { type: 'text', options: {"required":false,"label":"Teren","default":"Teren"} },
    touristTitle: { type: 'text', options: {"required":false,"label":"Informacje turystyczne","default":"Informacje turystyczne i audytowe"} },
    recommendationTitle: { type: 'text', options: {"required":false,"label":"Rekomendacja","default":"Rekomendacja końcowa"} },
    safetyTitle: { type: 'text', options: {"required":false,"label":"Bezpieczeństwo","default":"Bezpieczeństwo"} },
    backLink: { type: 'text', options: {"required":false,"label":"Link powrotu","default":"← Wróć do wszystkich tras"} },
    notFound: { type: 'text', options: {"required":false,"label":"Gdy trasy nie ma","default":"Nie znaleziono trasy"} },
  },
})
