import { defineCollection } from '#pruvious'

export default defineCollection({
  name: 'trails',
  mode: 'multi',
  translatable: false,
  apiRoutes: { read: 'public', readMany: 'public' },
  search: { default: [{ field: 'title', reserve: 30 }, 'teaser'] },
  dashboard: {
    primaryField: 'title',
    overviewTable: { sort: { field: 'title', direction: 'asc' }, perPage: 25 },
  },
  fields: {
    slug: { type: 'text', options: { required: true, description: 'Unikalny identyfikator w adresie URL, np. dolina-san-ustrzyki' } },
    title: { type: 'text', options: { required: true } },
    difficulty: { type: 'text', options: { required: true, description: 'latwa / srednia / trudna' } },
    bikeTypes: { type: 'text', options: { required: true, description: 'Oddzielone przecinkami: mtb, gravel, e-bike, szosa' } },
    lengthKm: { type: 'number', options: { required: true, label: 'Długość (km)', decimals: 1 } },
    elevationM: { type: 'number', options: { required: true, label: 'Przewyższenia (m)' } },
    durationHours: { type: 'text', options: { required: true, label: 'Czas przejazdu (tekst)' } },
    surfaceAsfalt: { type: 'number', options: { required: false, label: 'Nawierzchnia — asfalt (%)', default: 0 } },
    surfaceSzuter: { type: 'number', options: { required: false, label: 'Nawierzchnia — szuter (%)', default: 0 } },
    surfaceTeren: { type: 'number', options: { required: false, label: 'Nawierzchnia — teren (%)', default: 0 } },
    image: { type: 'text', options: { required: true, label: 'Zdjęcie główne (URL)' } },
    teaser: { type: 'text', options: { required: true, label: 'Krótki opis (1 zdanie)' } },
    description: { type: 'text-area', options: { required: false, label: 'Opis trasy (akapity oddzielone pustą linią)', rows: 6 } },
    highlights: { type: 'text-area', options: { required: false, label: 'Co warto zobaczyć (jedna pozycja na linię)', rows: 4 } },
    stops: { type: 'text-area', options: { required: false, label: 'Miejsca odpoczynku / gastronomia (jedna pozycja na linię)', rows: 4 } },
    safety: { type: 'text-area', options: { required: false, label: 'Bezpieczeństwo (jedna pozycja na linię)', rows: 4 } },
    gallery: { type: 'text-area', options: { required: false, label: 'Galeria — adresy URL zdjęć (jeden na linię)', rows: 3 } },
    gpxAvailable: { type: 'checkbox', options: { label: 'Plik GPX dostępny', default: false } },

    // --- Rozszerzone informacje o trasie (z opisu audytowego) ---
    gpxFile: { type: 'text', options: { required: false, label: 'Plik GPX (URL)', description: 'np. /gpx/nazwa-trasy.gpx' } },
    startFinish: { type: 'text', options: { required: false, label: 'Punkt startu / mety' } },
    routeCharacter: { type: 'text', options: { required: false, label: 'Charakter trasy', description: 'np. pętla, tam i z powrotem' } },
    recommendedBike: { type: 'text', options: { required: false, label: 'Rekomendowany rower (opis)', description: 'np. gravel / trekking / MTB' } },
    surfaceDescription: { type: 'text', options: { required: false, label: 'Nawierzchnia (opis słowny)' } },
    descentM: { type: 'number', options: { required: false, label: 'Suma zjazdów (m)' } },
    elevationMinM: { type: 'number', options: { required: false, label: 'Wysokość minimalna (m n.p.m.)' } },
    elevationMaxM: { type: 'number', options: { required: false, label: 'Wysokość maksymalna (m n.p.m.)' } },
    elevationDiffM: { type: 'number', options: { required: false, label: 'Różnica wysokości (m)' } },
    routeMapImage: { type: 'text', options: { required: false, label: 'Mapa przebiegu trasy (URL)' } },
    elevationProfileImage: { type: 'text', options: { required: false, label: 'Profil wysokościowy (URL)' } },
    waypoints: { type: 'text-area', options: { required: false, label: 'Najważniejsze punkty na trasie (jedna pozycja na linię: km | punkt | znaczenie)', rows: 8 } },
    routeOverview: { type: 'text-area', options: { required: false, label: 'Przebieg trasy (skrót)', rows: 3 } },
    naturalValues: { type: 'text-area', options: { required: false, label: 'Walory przyrodnicze', rows: 5 } },
    culturalValues: { type: 'text-area', options: { required: false, label: 'Walory historyczne i kulturowe', rows: 5 } },
    touristInfo: { type: 'text-area', options: { required: false, label: 'Informacje turystyczne', rows: 5 } },
    finalRecommendation: { type: 'text-area', options: { required: false, label: 'Rekomendacja końcowa', rows: 4 } },
    auditNotes: { type: 'text-area', options: { required: false, label: 'Uwagi audytowe / źródło (wewnętrzne)', rows: 5 } },
  },
})
